heat_template_version: queens

parameters:
  dns_zone:
    type: string
  public_key:
    type: string
    description: Public SSH key to use for cluster instances

resources:
  dns_random_string:
    type: OS::Heat::RandomString
    properties:
      character_classes: [ { "class": lowercase, "min": 10 } ]
      length: 10

  database_zone_name:
    type: OS::Heat::Value
    properties:
      value:
        list_join: [ '.', [ { get_resource: dns_random_string }, 'db', { get_param: dns_zone } ] ]
      type: string

  app_zone_name:
    type: OS::Heat::Value
    properties:
      value:
        list_join: [ '.', [ { get_resource: dns_random_string }, 'app', { get_param: dns_zone } ] ]
      type: string

  key_pair_name:
    type: OS::Heat::Value
    properties:
      value:
        list_join: [ '-', [ { get_resource: dns_random_string }, 'keypair' ] ]
      type: string

  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name:  { get_attr: [ key_pair_name, value ] }
      public_key: { get_param: public_key}
      save_private_key: false

outputs:
  dns_random_string:
    description: Generated suffix for DNS zone
    value: { get_attr: [ dns_random_string, value ] }
  key_pair_name:
    description: Name of key pair
    value: { get_attr: [ key_pair_name, value ] }
  database_dns_zone_name:
    description: The name for DNS zone with database refapp
    value: { get_attr: [ database_zone_name, value ] }
  app_dns_zone_name:
    description: The name for DNS zone with APPs refapp
    value: { get_attr: [ app_zone_name, value ] }
